### ISSUE TITLE
Vertical text

### ISSUE THREAD

**Issue by KannarFr** [builtamont-oss/play2-scala-pdf#39]
## Outcome Desired

Write vertical text in `@right-middle`.

I tried
```css
@@right-middle {
  content: "test;
  writing-mode: vertical-rl;
}
```

But it doesn't work. Any suggestion?
